#!/bin/bash
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

for all in *
do
    if [ "$all" = "postProcessing" ]
    then 
        rm -r postProcessing
    fi
    if [ "$all" = "logs" ]
    then 
        rm -r logs
    fi
done

cd system

for all in *
do
    if [ "$all" = "div" ]
    then 
        rm -r div
    elif [ "$all" = "cellMax" ]
    then 
        rm -r cellMax
    fi
done

echo "/*--------------------------------*- C++ -*----------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Version:  8
     \\/     M anipulation  |
-------------------------------------------------------------------------------
Description
    Calculates the divergence of a field.

\*---------------------------------------------------------------------------*/

type            div;
libs            (\"libfieldFunctionObjects.so\");

field           phi;

executeControl  writeTime;
writeControl    writeTime;

// ************************************************************************* //" >> div

echo "/*--------------------------------*- C++ -*----------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Version:  8
     \\/     M anipulation  |
-------------------------------------------------------------------------------
Description
    Writes out the maximum cell value for one or more fields.

\*---------------------------------------------------------------------------*/

#includeEtc \"caseDicts/postProcessing/minMax/cellMinMax.cfg\"

fields (U k epsilon M3);

// ************************************************************************* //" >> cellMax

cd ..

postProcess -func cellMax -latestTime

# Use this script for residuals plot
application=$(getApplication)
foamLog simulation.out

cd convergenceScripts
python3 main.py
